

version: '3.1'
services:
  ebank-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebank-digital-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/digital-bank
      - DB_USERNAME=root
      - DB_PASSWORD=pasroot
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
      

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pasroot
      MYSQL_DATABASE: digital-bank
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: root
